server:
  port: 8082
spring:
  application:
    name: ly-upload
  servlet:
    multipart:
      max-file-size: 5MB # 限制文件上传的大小
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 10
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true
ly:
  oss:
    accessKeyId: LTAI5t88KyE2BkRAhcHa27tG
    accessKeySecret: nL2nDeDgS1drvyRIwsW8bHTOR6vFCK
    host: http://ly-usian1.oss-cn-beijing.aliyuncs.com # 访问oss的域名，很重要bucket + endpoint
    endpoint: oss-cn-beijing.aliyuncs.com # 你的服务的端点，不一定跟我一样
    dir: "" # 保存到bucket的某个子目录
    expireTime: 20 # 过期时间，单位是S
    maxFileSize: 5242880 #文件大小限制，这里是5M